name: codeshield
description: "Project for ITE 010 A."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.11.0

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    flame: ^1.36.0
    carousel_slider: ^5.1.2
    faker: ^2.2.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/images/
        - assets/images/icons/
        - assets/images/profiles/
        - assets/fonts/
    fonts:
        - family: PixelifySans
          fonts:
              - asset: assets/fonts/PixelifySans-VariableFont_wght.ttf
